### ISSUE TITLE
Unknown Error w/ Cassandra 2.2 and Nightly on Insert

### ISSUE THREAD

**Issue by rschmukler** [tupshin/cassandra-rs#10]
Running the basic rust example results in "An unknown error occured" when building with cargo build.

Seems to be associated with binding variables to a statement, or inserting. Non-variable bound statement (eg. `session.execute("SELECT...`) work to read rows.

FWIW Running on OS X (El Capitan). Also apologies if I am leaving out something basic, new to the Rust world.

**Comment by tupshin** [comment]
Closing this unless somebody still has a problem running on OS X. I only test on Linux, but suspect this is a long fixed issue
