### ISSUE TITLE
println in get_column_by_name

### ISSUE THREAD

**Issue by den1zk** [tupshin/cassandra-rs#19]
Hi, 
I'm using get_column_by_name() function and since there is a println macro in it, it prints every row I get from DB. Can you please remove the println macro from that function?

**Comment by davideagen** [comment]
This appears to have been fixed by 7ee50de7221c8c6a7c9b8952774bd241c79c6695. There are no longer any println calls in non-example code for all of cassandra-rs and cassandra-sys-rs.
