### ISSUE TITLE
TableMeta should implement Display 

### ISSUE THREAD

**Issue by rustyrazorblade** [tupshin/cassandra-rs#22]
: the trait bound `cassandra::TableMeta: std::fmt::Display` is not satisfied [E0277]
src/main.rssrc/main.rs:188 :188             println!("Schema: {}", schema);

**Comment by cramertj** [comment]
The larger issue here is that all user-visible types should implement `Debug`.

**Comment by tupshin** [comment]
all public structs now implement Debug. I just added derive wherever it was missing. Custom Debug implementations for types that could benefit from it would be welcome
