### ISSUE TITLE
Timestamps

### ISSUE THREAD

**Issue by ernestas-poskus** [tupshin/cassandra-rs#31]
@tupshin @rustyrazorblade 

Currently it is almost impossible to work with Timestamp values how about implementing traits of `chrono` or `time` ? What do you think ?

**Comment by rustyrazorblade** [comment]
I'm definitely a +1 on proper timestamps.  How is this handled with other database drivers?  It would be nice if we could be consistent.  Which time trait are you referring to?

**Comment by bfrog** [comment]
sfacklers postgres optionally builds with chrono support, which I find extremely nice to work with. It also supports time, again as an optional dependency. Following the postgres client lead there probably makes a good deal of sense

**Comment by rustyrazorblade** [comment]
Got a link or example code that we could look at?  Would be nice to see the ergonomics.  Is this something you're interested in contributing?

**Comment by ernestas-poskus** [comment]
Indeed rust-postgres is a good example they implement both chrono and time here:

- https://github.com/sfackler/rust-postgres/blob/master/src/types/chrono.rs
- https://github.com/sfackler/rust-postgres/blob/master/src/types/time.rs

**Comment by tupshin** [comment]
I was seriously considering adding chrono integration previously, and didn't get to it then. Would welcome a PR for that if I don't get to it first.

**Comment by ernestas-poskus** [comment]
I am not sure how to implement it yet but I guess will get after few weeks when I will need it.
