### ISSUE TITLE
Planning to maintain this?

### ISSUE THREAD

**Issue by algermissen** [tupshin/cassandra-rs#37]
Hi,

can you share your plans for progress on this driver? I am about to build more than a toy project on top of Rust/C* and am looking for *the* driver to use.

Jan

**Comment by tupshin** [comment]
I think this is your best option. It's not an officially supported, but I would like to maintain it, and I'm interested in adding collaborators. Reviewing outstanding bugs and PRs now. Thanks very much for your interest

**Comment by algermissen** [comment]
Thanks a lot. I am C* user for 5 years now, Rust newbie but fully sold already. I'll try to help where I can.
