### ISSUE TITLE
Change are really breakin.. for 0.8.0

### ISSUE THREAD

**Issue by ernestas-poskus** [tupshin/cassandra-rs#42]
I get
```
thread '::test_find_one' panicked at 'called `Result::unwrap()` on an `Err` value: Error(LIB_NULL_VALUE(CASS_ERROR_LIB_NULL_VALUE), State { next_error: None, backtrace: None })', ../src/libcore/result.rs:837
```
https://github.com/tupshin/cassandra-rs/commit/2c57a8216e26cb7e16d46c2a718b171d5b1d0286

This is related to `to_result("").unwrap().into()`

**Comment by ernestas-poskus** [comment]
how about introducing tests and CI like Travis ?

**Comment by tupshin** [comment]
Apologies. Pin to 0.7 for now. I'll look into this over the next day or two
